import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import { SWRConfig } from "swr";
import Calculator from "@/components/calculator";
import OneSignalReact from "react-onesignal";

import Script from "next/script"; // 1. import next/script

export default function Home() {
  useEffect(() => {
    console.error("hakka");
    if ("serviceWorker" in navigator) {
      window.addEventListener("load", function () {
        navigator.serviceWorker.register("/service-worker.js").then(
          function (registration) {
            console.log(
              "ServiceWorker registration successful with scope: ",
              registration.scope
            );
          },
          function (err) {
            console.log("ServiceWorker registration failed: ", err);
          }
        );
      });
    }

    const init = async () => {
      try {
        await OneSignalReact.init({
          appId: "d5ed5df8-7d24-4f5e-82b7-d1007afae10f",
          allowLocalhostAsSecureOrigin: true,
        });
        await OneSignalReact.showSlidedownPrompt();
      } catch (error) {
        console.log("--------------");
        console.error(error);
      }
    };

    init();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        src="https://cdn.onesignal.com/sdks/OneSignalSDK.js"
        async
        strategy="lazyOnload"
      ></Script>
      <SWRConfig value={{ dedupingInterval: 60000 }}>
        <Calculator />
      </SWRConfig>
    </>
  );
}
